# Rock paper sciccors - part 1
"The first column is what your opponent is going to play: A for Rock, B for Paper, and C for Scissors. The second column--" Suddenly, the Elf is called away to help with someone's tent.

The second column, you reason, must be what you should play in response: X for Rock, Y for Paper, and Z for Scissors. Winning every time would be suspicious, so the responses must have been carefully chosen.

Your total score is the sum of your scores for each round. The score for a single round is the score for the shape you selected (1 for Rock, 2 for Paper, and 3 for Scissors) plus the score for the outcome of the round (0 if you lost, 3 if the round was a draw, and 6 if you won).

For example, suppose you were given the following strategy guide:

A Y
B X
C Z
This strategy guide predicts and recommends the following:

In the first round, your opponent will choose Rock (A), and you should choose Paper (Y). This ends in a win for you with a score of 8 (2 because you chose Paper + 6 because you won).
In the second round, your opponent will choose Paper (B), and you should choose Rock (X). This ends in a loss for you with a score of 1 (1 + 0).
The third round is a draw with both players choosing Scissors, giving you a score of 3 + 3 = 6.
In this example, if you were to follow the strategy guide, you would get a total score of 15 (8 + 1 + 6).

What would your total score be if everything goes exactly according to your strategy guide?

In [87]:
# removing the new line characters
with open('day2_input.txt') as f:
    lines = [line.rstrip() for line in f]

# scoring
A for Rock, B for Paper, and C for Scissors
X for Rock, Y for Paper, and Z for Scissors

scores for shape selected:
A, 1
B, 2
C, 3 
X, 1
Y, 2
Z, 3

score for outcome:
if scores are equal: 3
2 > 1
3 > 2
1 > 3

if abs(score1 - score2) = 1 then 6 for player with max score
else 3 for both

In [88]:
# import pandas as pd
import pandas as pd

# Calling DataFrame constructor on list
df = pd.DataFrame(lines)

In [89]:
df.head(6)

     0
0  A Y
1  B Y
2  B Z
3  B Z
4  B X
5  B Z

In [90]:
myscore = df[0].str[-1:]
df['myscore'] = myscore

opponentscore = df[0].str[:1]
df['opponentscore'] = opponentscore

df = df.replace(['A', 'B', 'C', 'X', 'Y', 'Z'], [1, 2, 3, 1, 2, 3])
#df['myscore'] = pd.to_numeric(df['myscore'], errors='coerce').astype('Int32')
#df['opponentscore'] = pd.to_numeric(df['opponentscore'], errors='coerce').astype('Int32')

In [91]:
df['outcome'] = df['myscore'] - df['opponentscore']

#df.loc[df['outcome'] == 1, 'mytotalscore'] == 6 #+ df['myscore']
#df.loc[df['outcome'] == 0, 'mytotalscore'] == 3 #+ df['myscore']
#df.loc[df['outcome'] == 2, 'mytotalscore'] == 0 #df['myscore']

df['myoutcomescore'] = df['outcome'].apply(lambda x: 
                                            6 if x == 1 
                                         else 6 if x == -2 
                                         else 3 if x == 0 
                                         else 0)

df['mytotalscore'] = df['myscore'] + df['myoutcomescore']

In [92]:
df.head(10)

     0  myscore  opponentscore  outcome  myoutcomescore  mytotalscore
0  A Y        2              1        1               6             8
1  B Y        2              2        0               3             5
2  B Z        3              2        1               6             9
3  B Z        3              2        1               6             9
4  B X        1              2       -1               0             1
5  B Z        3              2        1               6             9
6  C Y        2              3       -1               0             2
7  A Z        3              1        2               0             3
8  C X        1              3       -2               6             7
9  C X        1              3       -2               6             7

In [93]:
sum(df['mytotalscore'])

15422

# part 2
The Elf finishes helping with the tent and sneaks back over to you. "Anyway, the second column says how the round needs to end: X means you need to lose, Y means you need to end the round in a draw, and Z means you need to win. Good luck!"

The total score is still calculated in the same way, but now you need to figure out what shape to choose so the round ends as indicated. The example above now goes like this:

In the first round, your opponent will choose Rock (A), and you need the round to end in a draw (Y), so you also choose Rock. This gives you a score of 1 + 3 = 4.
In the second round, your opponent will choose Paper (B), and you choose Rock so you lose (X) with a score of 1 + 0 = 1.
In the third round, you will defeat your opponent's Scissors with Rock for a score of 1 + 6 = 7.
Now that you're correctly decrypting the ultra top secret strategy guide, you would get a total score of 12.

Following the Elf's instructions for the second column, what would your total score be if everything goes exactly according to your strategy guide?

In [101]:
# removing the new line characters
with open('day2_input.txt') as f:
    lines = [line.rstrip() for line in f]
df = pd.DataFrame(lines)

myresult = df[0].str[-1:]
df['myresult'] = myresult

opponentscore = df[0].str[:1]
df['opponentscore'] = opponentscore

# WIP

def conditions(s):
    if (s['myresult'] == 'Y' ):
        return s['opponentscore']
    if (s['myresult'] == 'X' ) and s['opponentscore'] == 'A':
            return 'Z'
    if (s['myresult'] == 'X' ) and s['opponentscore'] == 'B':
            return 'X'
    if (s['myresult'] == 'X' ) and s['opponentscore'] == 'C':
            return 'Y'
    if (s['myresult'] == 'Z' ) and s['opponentscore'] == 'A':
            return 'Y'
    if (s['myresult'] == 'Z' ) and s['opponentscore'] == 'B':
            return 'Z'
    if (s['myresult'] == 'Z' ) and s['opponentscore'] == 'C':
            return 'X'

df['myscore'] = df.apply(conditions, axis=1)

df = df.replace(['A', 'B', 'C', 'X', 'Y', 'Z'], [1, 2, 3, 1, 2, 3])
df['outcome'] = df['myscore'] - df['opponentscore']
df['myoutcomescore'] = df['outcome'].apply(lambda x: 
                                            6 if x == 1 
                                         else 6 if x == -2 
                                         else 3 if x == 0 
                                         else 0)

df['mytotalscore'] = df['myscore'] + df['myoutcomescore']
sum(df['mytotalscore'])

15442